baseURL = "http://datdiego.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "diego"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

publishDir = "docs"



[params]
  # DoIt theme version
  version = "0.2.X"
  googleAnalytics = "G-TLSLXTLD6R"

[params.author]
  name = "diego"
  link = "/about/"
  avatar = "/images/atoms_stars_data.jpg"

[params.footer]
    hugo = false

[params.image]
  # cache remote images for better optimisations
  cacheRemote = true
  # Image resizing and optimisation
  optimise = true


[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    # profile image
    avatarURL = "/images/atoms_stars_data.jpg"
    avatarLinkURL = "/about/"

    title = "Data Science, Physics, and Whatever This Is"

    subtitle = "Still figuring out if this is science or just really fancy guessing."
    # whether to use typeit animation for subtitle
    typeit = false

    social = true
  
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    hideDate = false
    hideCategories = true
    hideSeries = true
     
[params.sponsor]
    enable = true
    bio = "If you find this post helpful, please consider sponsoring."
    link = "https://www.buymeacoffee.com/datdiego" # The link to your sponsor page


[params.page]
    # DoIt NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # DoIt NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # DoIt NEW | 0.2.0 whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # DoIt NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # DoIt NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # DoIt NEW | 0.2.14 configure the link to the source file of the post
    linkToSource = false
    # "https://github.com/user/repo/blob/main/{path}"
    # DoIt NEW | 0.2.13 configure the link to edit the post
    linkToEdit = false
    # "https://github.com/user/repo/edit/main/{path}"
    # "https://gitlab.com/user/repo/-/edit/main/{path}"
    # "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
    # DoIt NEW | 0.2.14 configure the link to report issue for the post
    linkToReport = false
    # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
    # DoIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false
    # DoIt NEW | 0.2.13 whether to enable series navigation
    seriesNavigation = true
    # whether to enable last modified time
    enableLastMod = true
    # whether to enable word count
    enableWordCount = false
    # whether to enable reading time estimation
    enableReadingTime = false
    # DoIt NEW | 0.2.13 outdated article reminder config
    [params.page.outdatedArticleReminder]
      enable = false
      # Display the reminder if the last modified time is more than 90 days ago.
      reminder = 90
      # Display warning if the last modified time is more than 180 days ago.
      warning = 180
    # DoIt NEW | 0.2.0 Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = false
      # DoIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
      keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # DoIt CHANGED | 0.2.0 KaTeX mathematical formulas
    [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
      # Use MathJax instead of KaTeX
      mathjax = false
    # DoIt NEW | 0.2.0 Code config
    [params.page.code]
      # the maximum number of lines of displayed code by default
      maxShownLines = 200
      # whether to enable line numbers in the code block
      lineNos = true
      # whether to enable line wrapping in the code block
      wrap = false
      # whether to display the header in the code block
      header = true
    # DoIt NEW | 0.2.14 Table config
    [params.page.table]
      # whether to enable sorting in the tables
      sort = true
    # DoIt NEW | 0.2.0 Mapbox GL JS config
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # whether to add NavigationControl
      navigation = false
      # whether to add GeolocateControl
      geolocate = false
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
    # DoIt CHANGED | 0.2.0 social share links in post page
    [params.page.share]
      enable = false
      Twitter = false
      Facebook = false
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
      Mastodon = false
    # server for PlantUML online rendering
    [params.page.plantuml]
      server = "https://www.plantuml.com/plantuml"
    
        # instant.page config
    [params.page.instantpage]
      enable = false




  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    
  [params.social]
    Linkedin = "alducin-diego"
    Github = "datdiego"
    Kaggle = "ddelta"
    HuggingFace = "datdiego"
    Googlescholar = "https://scholar.google.com/citations?user=Rli2mWsAAAAJ&hl=en"

[menu]
  [[menu.main]]
    [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "😎 About me"
    url = "/about/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "📝 Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2

  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "#️⃣ Tags"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "📂 Categories"
    url = "/categories/"
    title = ""
    weight = 4

[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
