baseURL = "http://datdiego.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "diego"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

publishDir = "docs"

[params]
  # DoIt theme version
  version = "0.2.X"


[params.author]
  name = "diego"
  link = "/about/"
  avatar = "/images/atoms_stars_data.jpg"

[params.footer]
    hugo = false

[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    # profile image
    avatarURL = "/images/atoms_stars_data.jpg"
    avatarLinkURL = "/about/"

    title = "Data Science, Physics, and Whatever This Is"

    subtitle = "Still figuring out if this is science or just really fancy guessing."
    # whether to use typeit animation for subtitle
    typeit = true

    social = true
  
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
     

[params.social]
  Linkedin = "alducin-diego"
  Github = "datdiego"
  Kaggle = "ddelta"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  #[[menu.main]]
  #  identifier = "series"
  #  pre = ""
  #  post = ""
  #  name = "Series"
  #  url = "/series/"
  #  title = ""
  #  weight = 4
  #[[menu.main]]
  #  identifier = "authors"
  #  pre = ""
  #  post = ""
  #  name = "Authors"
  #  url = "/authors/"
  #  title = ""
  #  weight = 5
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4
  

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

